development:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  S3_BUCKET: 'app-vezva-assets'
test:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  S3_BUCKET: 'app-vezva-assets'
production:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY: 
  S3_BUCKET: 'app-vezva-assets'
